### ISSUE TITLE
Errors while gradlew build

### ISSUE THREAD

**Issue by YogeshDoke** [Raysmond/SpringBlog#10]
~/SpringBlog-master$  ./gradlew build                                                   
                                                              
:compileJava
FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not resolve org.springframework.boot:spring-boot-starter-log4j:1.4.0.RELEASE.
  Required by:
      :SpringBlog:0.1
   > Could not resolve org.springframework.boot:spring-boot-starter-log4j:1.4.0.RELEASE.
      > Could not get resource 'http://repo.springsource.org/repo/org/springframework/boot/spring-boot-starter-log4
j/1.4.0.RELEASE/spring-boot-starter-log4j-1.4.0.RELEASE.pom'.
         > Could not GET 'http://repo.springsource.org/repo/org/springframework/boot/spring-boot-starter-log4j/1.4.
0.RELEASE/spring-boot-starter-log4j-1.4.0.RELEASE.pom'. Received status code 401 from server: Unauthorized
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED

**Comment by Raysmond** [comment]
The latest version of spring-boot-starter-log4j pom is 1.3.7.RELEASE, not 1.4.0.RELEASE. It's already fixed. Please update your local repository.
