### ISSUE TITLE
js和一些css静态资源请求不到。json转换报错。

### ISSUE THREAD

**Issue by gonefuture** [Raysmond/SpringBlog#30]
![image](https://user-images.githubusercontent.com/19575771/43071909-d50af39e-8ea6-11e8-93bb-8956c0e36663.png)

**Comment by zooooooooy** [comment]
静态资源  springboot 需要放在static，public等目录下

看看是不是这个wen问题导致的

**Comment by gonefuture** [comment]
这个是我我没修改项目的代码的情况下发生的，，奇怪的是我在static，public目录下并没有发现这些文件。 @zooooooooy

**Comment by zooooooooy** [comment]
我之前好早的时候跑过这个项目，跑起来就没管了。他的jquery是用webjars加载的。
https://gitee.com/zooy/SpringBlog
这个是码云 之前跑过的 fork作者的项目  你看看，他这个项目要先建好库的。数据库表是自动生成的。

**Comment by gonefuture** [comment]
可能版本不一样吧。

**Comment by zooooooooy** [comment]
嗯，没事 感觉你琢磨一会 应该就能成功的。

**Comment by gonefuture** [comment]
谢谢。不过我转而想用码云上的DBlog这个项目了。我本来是想找个基于SpringBoot的开源博客项目挂到自己的个人网站上的，你有什么好推荐吗？

**Comment by zooooooooy** [comment]
我一开始准备这么弄，后来觉得这一套挺麻烦的，用的是静态的。hexo来做的网站，需要你自己处理一下图片文件的存储。你可以用github或者gitee的webhook来推送你文章。我的网站db101.cn 你看能看的上眼不。

**Comment by gonefuture** [comment]
感觉很好啊，你有模板这些资料吧，我也想弄一个。

**Comment by zooooooooy** [comment]
https://gitee.com/zooy/TBlog  是这个项目， 你可以挑一个你看顺眼的hexo主题。

**Comment by gonefuture** [comment]
好的，谢谢。我看看要怎么弄。

**Comment by gonefuture** [comment]
@zooooooooy 你好，请问你用的是什么主题，我复制你的项目后，发现主题是github默认的主题，一些css资源和图片资源都失效了，那个方块和音乐播放不见了，请问有主题和图片的资源吗？

**Comment by zooooooooy** [comment]
音乐播放器用的是网易云音乐，你需要自己处理一下文件的访问。我是用openresty（nginx）代理的css，图片等

**Comment by Yaredgroovy** [comment]
readme 已经讲的很清楚了，通过bower install下载这些资源文件就有了

**Comment by gonefuture** [comment]
@AndrRousite 好的
