### ISSUE TITLE
关于SLF4J的相关警告信息

### ISSUE THREAD

**Issue by tianshuang** [Raysmond/SpringBlog#4]
在执行bootRun时控制台打印出以下警告：

`SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/tspoi/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/tspoi/.m2/repository/org/slf4j/slf4j-log4j12/1.7.12/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]`

[Declaring project dependencies for logging](http://www.slf4j.org/manual.html#projectDep)

在build.gradle里是否声明了不必要的依赖？
尝试注释以下三行后重新执行bootRun，warn相关信息消除。

> compile 'org.springframework.boot:spring-boot-starter-log4j:1.3.0.M5'
> compile 'org.slf4j:slf4j-api:+'
> compile 'org.apache.commons:commons-lang3:+'

**Comment by Raysmond** [comment]
请更新代码，再跑！
