### ISSUE TITLE
博客中的图片处理

### ISSUE THREAD

**Issue by pjzhong** [Raysmond/SpringBlog#5]
博主，能问下你是如何处理文章中的图片？

**Comment by Raysmond** [comment]
没有做图片处理，推荐上传图片到云存储（比如七牛 https://github.com/qiniu/java-sdk）。访问速度，图片处理都比较给力。

**Comment by pjzhong** [comment]
谢了！

**Comment by pjzhong** [comment]
博主，你就是直接把博客中的图片上传到云存储里面去，然后要看的时候再去拿？

**Comment by Raysmond** [comment]
上传云存储之后，把URL记住就行了。
