### ISSUE TITLE
Errror in starting application

### ISSUE THREAD

**Issue by laozhuang727** [Raysmond/SpringBlog#9]
hi Raysmond,

when I started the application with ./gradlew bootRun, it got below error:

2016-07-31 10:08:26.263 [main] DEBUG com.raysmond.blog.Application - Running with Spring Boot v1.3.0.M5, Spring v4.2.7.RELEASE
2016-07-31 10:08:26.457 [main] ERROR o.s.boot.SpringApplication - Application startup failed
Exception in thread "main" java.lang.NoSuchMethodError: org.springframework.core.annotation.AnnotationAttributes.getAliasedStringArray(Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)[Ljava/lang/String;

is it because the Spring core version we used are invalid?

**Comment by acidlychee** [comment]
maybe due to version conflict..看一下libs，是不是有两个不同版本的spring jar

**Comment by laozhuang727** [comment]
是的，我指定了具体的版本后就没有问题了

**change from**
compile 'org.springframework:spring-orm:+'
compile 'org.hibernate:hibernate-entitymanager:+'

**to**
compile 'org.springframework:spring-orm:4.2.7.RELEASE'
compile 'org.hibernate:hibernate-entitymanager:4.3.11.Final'
    
Done

**Comment by laozhuang727** [comment]
还有一个问题，为什么作者要这样设置：
![image](https://cloud.githubusercontent.com/assets/9363875/17275200/0063ab34-5732-11e6-97e8-c8372b3e4c28.png)

这导致了如果直接在idea中启动application会jade页面找不到

报如下错误：
TemplateInputException: Error resolving template "home/index", template might not exist or might not be accessible by any of the configured Template Resolvers





**改为这样后ok**
![image](https://cloud.githubusercontent.com/assets/9363875/17275203/15ceae10-5732-11e6-8ab5-735d4b2af160.png)

**Comment by YogeshDoke** [comment]
i am having same problem what i have to do exactly

**Comment by Raysmond** [comment]
I already updated the versions of Spring Boot and Spring Framework and tested in Intellij IDEA. Please update your repository and follow the new [instructions ](https://github.com/Raysmond/SpringBlog#development-1)to import the project into your IDEA. I should be okay.
